# Generated by Django 4.2 on 2023-05-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_enquete', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='qustion',
            new_name='question',
        ),
    ]
